### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by pablorq** [nunux-keeper/keeper-core-api#17]
Hi!

The system seems nice. Do you have a tutorial?

Regards...

**Comment by ncarlier** [comment]
Hello,

What kind of tutorial would you like? For installation, use?
I don't know if it helps, but for the installation there is a tutorial (relying on Docker) here:  https://github.com/nunux-keeper/keeper-docker

Regards

**Comment by pablorq** [comment]
Hi,

I mean a tutorial for use. Or just a video of how to do the things.

Thank you in advance.

Regards

**Comment by ncarlier** [comment]
Hi,

just FYI I working on a online documentation. I expect to release a first draft in a couple of days.

Regards

**Comment by ncarlier** [comment]
Hi,
a french documentation is up and running here: https://keeper.nunux.org/doc/fr/
English translation will come in next days.

Regards

**Comment by ncarlier** [comment]
English documentation is also up and running: https://keeper.nunux.org/doc/en/

Regards
